version: 0.0.{build}

services:
  - mssql2017
  - postgresql

build:
  publish_nuget: true

build_script:
  - ps: .\build.ps1 -Target Pack -Verbosity Diagnostic

artifacts:
  - path: Kimos\bin\Release\*.nupkg

deploy:
  - provider: NuGet
    api_key:
      secure: GMc0xUTASI8qTPK1/eN/GFs6PBhPFBin1TT1hE5N8NlkU7VSBx3z4zQinSv/ICmx
    artifact: /.*\.nupkg/
